#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP response header

# Update packages and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Set default index page
echo "Holberton School" | sudo tee /var/www/html/index.html

# Add custom HTTP header to Nginx config
sudo sed -i '/server_name _;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
