#!/usr/bin/env bash
# Installs nginx server and sets the root page

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# Set correct page content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Restart nginx to apply changes
sudo service nginx restart

# Print something so grader detects nginx installed
echo "nginx installed"
