#!/usr/bin/env bash
# Install Nginx and configure root page to return exact Holberton School

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

service nginx restart
