#!/usr/bin/env bash
#Installs nginx server and sets the root page

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
