#!/usr/bin/env bash
# Configures Nginx with a 301 redirect on /redirect_me

sudo apt-get update -y
sudo apt-get install -y nginx

# Optional: set default page content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Add /redirect_me 301 redirect using sed
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
